---
title: "NYC_inspections Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(flexdashboard)
library(plotly)
library(httr)
library(jsonlite)
```

```{r, include=FALSE}
get_all_inspections = function(url) {
  
  all_inspections = vector("list", length = 0)
  
  loop_index = 1
  chunk_size = 50000
  DO_NEXT = TRUE
  
  while (DO_NEXT) {
    message("Getting data, page ", loop_index)
    
    all_inspections[[loop_index]] = 
      GET(url,
          query = list(`$order` = "zipcode",
                       `$limit` = chunk_size,
                       `$offset` = as.integer((loop_index - 1) * chunk_size)
                       )
          ) %>%
      content("text") %>%
      fromJSON() %>%
      as_tibble()
    
    DO_NEXT = dim(all_inspections[[loop_index]])[1] == chunk_size
    loop_index = loop_index + 1
  }
  
  all_inspections
  
}

url = "https://data.cityofnewyork.us/resource/43nn-pn8j.json"

nyc_inspections = 
  get_all_inspections(url) %>%
  bind_rows() 
```

```{r, include=FALSE}
nyc = nyc_inspections %>% 
  select(score,boro,camis, grade, latitude, longitude,street, cuisine_description) %>% 
  filter(score %in% 20:100, latitude >0) %>% 
  drop_na(grade)
```
Column {data-width=650}
-----------------------------------------------------------------------

### The restaurant scores in Manhattan area

```{r}
nyc %>%
  filter(boro == "Manhattan") %>%
  plot_ly(x = ~ latitude,y =  ~ longitude,color = ~ score,type = "scatter",
mode = "markers", alpha = .5,text = ~ score) %>%
  layout((title = "The restaurant scores in Manhattan area"),
         xaxis = list(title = "latitude"),
         yaxis = list(title = "longitude"))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Restaurant scores in different areas 

```{r}
nyc %>% 
  mutate(street = fct_reorder(boro, score)) %>% 
  plot_ly(x=~boro, y= ~score, color = ~street, type= "box", colors= "viridis") %>% 
  layout((title = "Restaurant scores in different areas"),
          xaxis = list(title = "Borough"),
          yaxis = list(title = "Restaurant scores"))
```

### Score ranking of different cuisine 

```{r}
nyc %>% 
  count(cuisine_description) %>% 
  mutate(cuisine_description = fct_reorder(cuisine_description, n)) %>% 
  plot_ly(x=~cuisine_description, y=~n, type="bar") %>% 
    layout((title = "Scores Ranking of different cursine"),
          xaxis = list(title = "Cuisine Type"),
          yaxis = list(title = "Inspection Scores"))
```

